siteTitle: Euaggelion
siteDescription: Semeando as boas novas da salvação
metaTitle: Euaggelion | Semeando as boas de salvação
metaDescription: >-
  Devocionais, estudos bíblicos, materiais e outros recursos gratuitos para
  edificar a sua fé.
