// Este arquivo contém os dados básicos dos livros para evitar o uso de 'fs' no Client Side
export const BIBLE_BOOKS_MAP: Record<string, string> = {
  "gênesis": "genesis", "gn": "genesis",
  "êxodo": "exodo", "êx": "exodo",
  "levítico": "levitico", "lv": "levitico",
  "números": "numeros", "nm": "numeros",
  "deuteronômio": "deuteronomio", "dt": "deuteronomio",
  "josué": "josue", "js": "josue",
  "juízes": "juizes", "jz": "juizes",
  "rute": "rute", "rt": "rute",
  "1 samuel": "1samuel", "1sm": "1samuel",
  "2 samuel": "2samuel", "2sm": "2samuel",
  "1 reis": "1reis", "1rs": "1reis",
  "2 reis": "2reis", "2rs": "2reis",
  "1 crônicas": "1cronicas", "1cr": "1cronicas",
  "2 crônicas": "2cronicas", "2cr": "2cronicas",
  "esdras": "esdras", "ed": "esdras",
  "neemias": "neemias", "ne": "neemias",
  "ester": "ester", "et": "ester",
  "jó": "jo",
  "salmos": "salmos", "sl": "salmos",
  "salmo": "salmos",
  "provérbios": "proverbios", "pv": "proverbios",
  "eclesiastes": "eclesiastes", "ec": "eclesiastes",
  "cânticos": "canticos", "ct": "canticos",
  "isaías": "isaias", "is": "isaias",
  "jeremias": "jeremias", "jr": "jeremias",
  "lamentações": "lamentacoes-de-jeremias", "lm": "lamentacoes-de-jeremias",
  "ezequiel": "ezequiel", "ez": "ezequiel",
  "daniel": "daniel", "dn": "daniel",
  "oséias": "oseias", "os": "oseias",
  "joel": "joel", "jl": "joel",
  "amós": "amos", "am": "amos",
  "obadias": "obadias", "ob": "obadias",
  "jonas": "jonas", "jn": "jonas",
  "miquéias": "miqueias", "mq": "miqueias",
  "naum": "naum", "na": "naum",
  "habacuque": "habacuque", "hc": "habacuque",
  "sofonias": "sofonias", "sf": "sofonias",
  "ageu": "ageu", "ag": "ageu",
  "zacarias": "zacarias", "zc": "zacarias",
  "malaquias": "malaquias", "ml": "malaquias",
  "mateus": "mateus", "mt": "mateus",
  "marcos": "marcos", "mc": "marcos",
  "lucas": "lucas", "lc": "lucas",
  "joão": "joao", "jo": "joao",
  "atos": "atos", "at": "atos",
  "romanos": "romanos", "rm": "romanos",
  "1 coríntios": "1corintios", "1co": "1corintios",
  "2 coríntios": "2corintios", "2co": "2corintios",
  "gálatas": "galatas", "gl": "galatas",
  "efésios": "efesios", "ef": "efesios",
  "filipenses": "filipenses", "fp": "filipenses",
  "colossenses": "colossenses", "cl": "colossenses",
  "1 tessalonicenses": "1tessalonicenses", "1ts": "1tessalonicenses",
  "2 tessalonicenses": "2tessalonicenses", "2ts": "2tessalonicenses",
  "1 timóteo": "1timoteo", "1tm": "1timoteo",
  "2 timóteo": "2timoteo", "2tm": "2timoteo",
  "tito": "tito", "tt": "tito",
  "filemom": "filemom", "fm": "filemom",
  "hebreus": "hebreus", "hb": "hebreus",
  "tiago": "tiago", "tg": "tiago",
  "1 pedro": "1pedro", "1pe": "1pedro", "1 pe": "1pedro", "i pedro": "1pedro", "i pe": "1pedro",
  "2 pedro": "2pedro", "2pe": "2pedro", "2 pe": "2pedro", "ii pedro": "2pedro", "ii pe": "2pedro",
  "1 joão": "1joao", "1jo": "1joao",
  "2 joão": "2joao", "2jo": "2joao",
  "3 joão": "3joao", "3jo": "3joao",
  "judas": "judas", "jd": "judas",
  "apocalipse": "apocalipse", "ap": "apocalipse"
};
