"""
Initializes the Bíblia.academy development environment.

Usage:
python3 scripts/dev.py

Steps:

1. Installs Python dependencies from scripts/ (if scripts/requirements.txt exists).
2. Installs JS dependencies via pnpm, if the monorepo has a workspace configured
(pnpm-workspace.yaml) — this is not yet the case, as the apps haven't been created.
3. Generates/updates content/modules.json based on the actual state of /content
(see scripts/generate_content_index.py).
4. Prompts for external API tokens (see REQUIRED_ENV_VARS below) and saves them to
.env.local, which is never committed. Also (re)generates .env.example, the committed
reference of which variables the project expects.

This is intended both for starting development here and for anyone who forks the
project and needs to set up their own local environment.

"""

from __future__ import annotations

import getpass
import os
import subprocess
import sys

from _common import ENV_LOCAL_PATH, PROJECT_ROOT, parse_env_file

ENV_EXAMPLE_PATH = PROJECT_ROOT / ".env.example"

# Registry of external API tokens the project needs. Add an entry here whenever a
# new module/integration requires its own token — dev.py will prompt for it and
# keep .env.example in sync automatically.
REQUIRED_ENV_VARS = [
    {
        "key": "DEEPSEEK_API_KEY",
        "label": "DeepSeek API key",
        "prompt": "Paste your DeepSeek API key (https://platform.deepseek.com/api_keys)",
    },
]


def run(cmd: list[str]) -> bool:
    print(f"$ {' '.join(cmd)}")
    result = subprocess.run(cmd, cwd=PROJECT_ROOT)
    return result.returncode == 0


def install_python_dependencies() -> None:
    requirements = PROJECT_ROOT / "scripts" / "requirements.txt"
    if not requirements.exists():
        print("[python] No dependencies declared in scripts/requirements.txt — skipping.")
        return
    print("[python] Installing script dependencies/requirements.txt")
    if not run([sys.executable, "-m", "pip", "install", "-r", str(requirements)]):
        print("[python] Failed to install dependencies.", file=sys.stderr)
        sys.exit(1)

def install_js_dependencies() -> None:
    if not (PROJECT_ROOT / "pnpm-workspace.yaml").exists():
        print("[js] no pnpm workspace found yet (apps/ not created) — skipping.")
        return
    print("[js] installing dependencies via pnpm...")
    if not run(["pnpm", "install"]):
        print("[js] Failed to install dependencies.", file=sys.stderr)
        sys.exit(1)

def generate_content_index() -> None:
    print("[content] generating content/modules.json from /content...")
    import generate_content_index as gci

    gci.main()


def mask(value: str) -> str:
    if len(value) <= 8:
        return "*" * len(value)
    return f"{value[:4]}...{value[-4:]}"


def write_env_example() -> None:
    lines = [
        "# Auto-generated by scripts/dev.py from REQUIRED_ENV_VARS.",
        "# Copy to .env.local and fill in real values (.env.local is never committed).",
        "",
    ]
    for var in REQUIRED_ENV_VARS:
        lines.append(f"# {var['label']}")
        lines.append(f"{var['key']}=")
        lines.append("")
    ENV_EXAMPLE_PATH.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def is_interactive() -> bool:
    # getpass.getpass() reads straight from the console on Windows (via msvcrt),
    # bypassing a redirected stdin — isatty() alone can't detect that case, so CI
    # (or anything scripted) must opt out explicitly via one of these env vars.
    if os.environ.get("CI") or os.environ.get("BIBLIA_ACADEMY_NONINTERACTIVE"):
        return False
    return sys.stdin.isatty() and sys.stdout.isatty()


def configure_env_tokens() -> None:
    write_env_example()

    existing_lines = (
        ENV_LOCAL_PATH.read_text(encoding="utf-8").splitlines()
        if ENV_LOCAL_PATH.exists()
        else []
    )
    existing_values = parse_env_file(ENV_LOCAL_PATH)
    interactive = is_interactive()
    updated_lines = list(existing_lines)
    changed = False

    for var in REQUIRED_ENV_VARS:
        key = var["key"]
        current = existing_values.get(key)
        if current:
            print(f"[env] {key} already set ({mask(current)}) — skipping.")
            continue

        if not interactive:
            print(
                f"[env] {key} not set — running non-interactively, skipping. "
                "Set it manually in .env.local later."
            )
            continue

        try:
            value = getpass.getpass(f"[env] {var['prompt']}\n> ").strip()
        except EOFError:
            value = ""

        if not value:
            print(f"[env] {key} left empty — you can set it later in .env.local.")
            continue

        line = f"{key}={value}"
        for i, existing_line in enumerate(updated_lines):
            if existing_line.startswith(f"{key}="):
                updated_lines[i] = line
                break
        else:
            updated_lines.append(line)
        changed = True
        print(f"[env] {key} saved to .env.local ({mask(value)}).")

    if changed:
        ENV_LOCAL_PATH.write_text(
            "\n".join(updated_lines).rstrip() + "\n", encoding="utf-8"
        )


def main() -> None:
    print("\033c", end="")
    print("===========================================================")
    print("biblia.academy - development environment initialization")
    print("===========================================================")
    print("\n")
    install_python_dependencies()
    install_js_dependencies()
    generate_content_index()
    configure_env_tokens()
    print("\n")
    print("Done! Environment initialized.")

if __name__ == "__main__":
    main()